[tool.poetry]
name = "EiMM Hostbot"
version = "0.1.0"
description = "EiMM hostbot for eimm things"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9.10"
PyYAML = "^6.0"
numpy = "^1.22.3"
fuzzywuzzy = "^0.18.0"
dice = "^3.1.2"
imgurpython = "^1.1.7"
munkres = "^1.1.4"
oauth2client = "^4.1.3"
Pillow = "^9.0.1"
pycountry = "^22.3.5"
python-Levenshtein = "^0.12.2"
pytz = "^2022.1"
SQLAlchemy = "^1.4.32"
"discord.py" = {git = "https://github.com/Rapptz/discord.py.git", rev = "master"}
gspread-asyncio = "^1.5.3"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
ipython = "^8.1.1"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
